#!/bin/sh

# Source function library.
. /etc/init.d/functions

NODE_EXPORTER_BIN=$NODE_EXPORTER_PATH/node_exporter
WEB_LISTEN_ADDRESS=:9100
PIDFILE=/var/run/node_exporter.pid

start() {
    echo -n "Starting Prometheus: "
    if [ -f $PIDFILE ]; then
        echo "Prometheus is already running."
        exit 1
    fi
    daemon --pidfile=$PIDFILE $NODE_EXPORTER_BIN \
           --web.listen-address=$WEB_LISTEN_ADDRESS
    RETVAL=$?
    [ $RETVAL -eq 0 ] && echo $! > $PIDFILE
    echo
    return $RETVAL
}

stop() {
    echo -n "Stopping Prometheus: "
    if [ ! -f $PIDFILE ]; then
        echo "Prometheus is not running."
        exit 1
    fi
    killproc -p $PIDFILE $NODE_EXPORTER_BIN
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f $PIDFILE
    echo
    return $RETVAL
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status -p $PIDFILE $NODE_EXPORTER_BIN
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
exit 0
